### ISSUE TITLE
header not found

### ISSUE THREAD

**Issue by Wistral** [expnkx/fast_io_examples#1]
examples in [0006.codecvt](https://github.com/expnkx/fast_io_examples/tree/master/0006.codecvt)

include sentences:

>#include"../../include/fast_io.h"
>#include"../../include/fast_io_device.h"
>#include"../../include/fast_io_legacy.h"
>#include"../timer.hh"

#### `"../timer.hh"` is not provided

if I just comment it, got
>error: ‘timer’ is not a member of ‘fast_io’

**Comment by expnkx** [comment]
fixed
